### Create and Update CDA maps for converting to FHIR with RESTClient and running matchbox
### Note: POST the maps in the following order, if you update one map you need to repost also the maps below

# Own matchbox instance

# current matchbox
# @host = http://localhost:8080/matchboxv3/fhir
# matchbox 2.3.0
@host = http://localhost:8080/matchbox/fhir

### Capability Statement
GET {{host}}/metadata HTTP/1.1
Content-Type: application/fhir+json;fhirVersion=4.0

### StructureMap
GET {{host}}/StructureMap/
Accept: application/fhir+xml;fhirVersion=4.0.1
Content-Type: application/fhir+xml;fhirVersion=4.0.1

### StructureDefinition
GET {{host}}/StructureDefinition/ClinicalDocument
Accept: application/fhir+xml
Content-Type: application/fhir+xml

### StructureMap
GET {{host}}/StructureMap/at-cda-to-bundle
Accept: application/fhir+xml
Content-Type: application/fhir+xml

### StructureMap
GET {{host}}/StructureMap/?url=http://hl7.at/fhir/HL7ATCoreProfiles/4.0.1/StructureMap/at-cda-to-bundle
Accept: application/fhir+xml
Content-Type: application/fhir+xml

### StructureMap-Ressorces ---------------------------------------------------------------------

### 1.a. POST CdaToFhirTypes.map
POST {{host}}/StructureMap HTTP/1.1
Accept: application/fhir+xml;fhirVersion=4.0.1
Content-Type: text/fhir-mapping

< ./maps/CdaToFhirTypes.map

### 1.b. POST CdaToBundle.map
POST {{host}}/StructureMap HTTP/1.1
Accept: application/fhir+xml;fhirVersion=4.0.1
Content-Type: text/fhir-mapping

< ./maps/CdaToBundle.map

### 1.c. POST AtBundleToEuBundle.map
POST {{host}}/StructureMap HTTP/1.1
Accept: application/fhir+xml;fhirVersion=4.0.1
Content-Type: text/fhir-mapping

< ./maps/AtBundleToEuBundle.map

### Execution of Transformation ----------------------------------------------------------------------

### 2.a. POST Lab_Allgemeiner_Laborbefund.xml (CdaToBundle)
POST {{host}}/StructureMap/$transform?source=http://hl7.at/fhir/HL7ATCoreProfiles/4.0.1/StructureMap/at-cda-to-bundle
Accept: application/fhir+xml;fhirVersion=4.0.1
Content-Type: application/fhir+xml;fhirVersion=4.0.1

< ./input/Lab_Allgemeiner_Laborbefund.xml

### 2.b. POST Mibi_Mikrobiologie.xml (CdaToBundle)
POST {{host}}/StructureMap/$transform?source=http://hl7.at/fhir/HL7ATCoreProfiles/4.0.1/StructureMap/at-cda-to-bundle
Accept: application/fhir+xml;fhirVersion=4.0.1
Content-Type: application/fhir+xml;fhirVersion=4.0.1

< ./input/Mibi_Mikrobiologie.xml

### 2.a. POST ELGA-043-Laborbefund_EIS-FullSupport (CdaToBundle)
POST {{host}}/StructureMap/$transform?source=http://hl7.at/fhir/HL7ATCoreProfiles/4.0.1/StructureMap/at-cda-to-bundle
Accept: application/fhir+xml;fhirVersion=4.0.1
Content-Type: application/fhir+xml;fhirVersion=4.0.1

< ./input/ELGA-043-Laborbefund_EIS-FullSupport.xml

### AT to EU ----------------------------------------------------------------------

POST {{host}}/StructureMap/$transform?source=http://hl7.at/fhir/HL7ATCoreProfiles/4.0.1/StructureMap/at-bundle-to-eu-bundle
Accept: application/fhir+xml;fhirVersion=4.0.1
Content-Type: application/fhir+xml;fhirVersion=4.0.1

< ./input/FHIR_AT_Lab.xml

