@startuml

title FHIR IG Laboratory - Relationship FHIR Resources

class Composition
class DiagnosticReport
class Patient
class Observation
class Specimen
class ServiceRequest
class Device
class Section
class Encounter
class Organization
class PractitionerRole
class Practitioner
class Location

Composition o-- "0..*" Device : author
Composition o-- "1..1" Organization : custodian
Composition o-- "1..*" PractitionerRole : author
Composition o-- "1..1" PractitionerRole : attester (legal)
Composition o-- "0..1" Encounter : encounter
Composition o-- "0..*" Section
Composition o-- "1..1" DiagnosticReport : subject

DiagnosticReport o-- "1..*" Specimen : specimen
DiagnosticReport o-- "1..1" Patient : subject
DiagnosticReport o-- "0..1" ServiceRequest : basedOn

Patient o-- "0..*" Organization : contact

Specimen o-- "1..1" Patient : subject

ServiceRequest o-- "0..1" PractitionerRole : requester

Section o-- "0..*" Observation : entry

Device o-- "0..1" Organization : owner

PractitionerRole o-- "0..1" Organization : organization
PractitionerRole o-- "0..1" Practitioner : practitioner

Encounter o-- "0..*" PractitionerRole : participant
Encounter o-- "0..*" Location : location

Location o-- "0..1" Organization : managingOrganization

@enduml